/******************************************************************************/
/*            Generated by IBExpert 2023.1.3.1 28/02/2023 10:27:09            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

CREATE DATABASE 'C:\ControleTicket\Database\ticket.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/*                                  Domains                                   */
/******************************************************************************/

CREATE DOMAIN DOM_CHAR1 AS
CHAR(1);

CREATE DOMAIN DOM_INTEGER AS
INTEGER;

CREATE DOMAIN DOM_TIMESTAMP AS
TIMESTAMP;

CREATE DOMAIN DOM_VARCHAR11 AS
VARCHAR(11);

CREATE DOMAIN DOM_VARCHAR60 AS
VARCHAR(60);



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_FUNCIONARIO_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_FUNCIONARIO_ID TO 0;

CREATE GENERATOR GEN_TICKETFUNCIONARIO_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_TICKETFUNCIONARIO_ID TO 0;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE FUNCIONARIO (
    ID              DOM_INTEGER NOT NULL,
    CPF             DOM_VARCHAR11 NOT NULL,
    NOME            DOM_VARCHAR60 NOT NULL,
    SITUACAO        DOM_CHAR1 DEFAULT 'A' NOT NULL,
    DATA_ALTERACAO  DOM_TIMESTAMP NOT NULL
);

CREATE TABLE TICKETFUNCIONARIO (
    ID              DOM_INTEGER NOT NULL,
    ID_FUNCIONARIO  DOM_INTEGER NOT NULL,
    QUANTIDADE      DOM_INTEGER NOT NULL,
    SITUACAO        DOM_CHAR1 DEFAULT 'A' NOT NULL,
    DATA_ENTREGA    DOM_TIMESTAMP NOT NULL
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID);
ALTER TABLE TICKETFUNCIONARIO ADD CONSTRAINT PK_TICKETFUNCIONARIO PRIMARY KEY (ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE TICKETFUNCIONARIO ADD CONSTRAINT FK_TICKETFUNCIONARIO_1 FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID) ON DELETE CASCADE ON UPDATE CASCADE;


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: FUNCIONARIO_BI */
CREATE TRIGGER FUNCIONARIO_BI FOR FUNCIONARIO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_funcionario_id,1);
end
^

/* Trigger: TICKETFUNCIONARIO_BI */
CREATE TRIGGER TICKETFUNCIONARIO_BI FOR TICKETFUNCIONARIO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_ticketfuncionario_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/*                            Fields descriptions                             */
/******************************************************************************/

COMMENT ON COLUMN FUNCIONARIO.ID IS
'Identificador do Funcionário';

COMMENT ON COLUMN FUNCIONARIO.CPF IS
'CPF do funcionário';

COMMENT ON COLUMN FUNCIONARIO.NOME IS
'Nome do funcionário';

COMMENT ON COLUMN FUNCIONARIO.SITUACAO IS
'Identifica se o cadastro está ativo (A) ou inativo (I). Por padrão Ativo (A)';

COMMENT ON COLUMN FUNCIONARIO.DATA_ALTERACAO IS
'Última data e hora que foi alterado o cadastro';

COMMENT ON COLUMN TICKETFUNCIONARIO.ID IS
'Identificador do Ticket';

COMMENT ON COLUMN TICKETFUNCIONARIO.ID_FUNCIONARIO IS
'Identificador do Funcionário';

COMMENT ON COLUMN TICKETFUNCIONARIO.QUANTIDADE IS
'Quantidade de Ticket Entregue';

COMMENT ON COLUMN TICKETFUNCIONARIO.SITUACAO IS
'Identifica se o cadastro está ativo (A) ou inativo (I). Por padrão Ativo (A)';

COMMENT ON COLUMN TICKETFUNCIONARIO.DATA_ENTREGA IS
'Data e hora que foi entregue o ticket';

